name: Build APK

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    steps:
      - uses: actions/checkout@v4
      
      - name: Gerekli sistem paketlerini kur
        run: |
          sudo apt update
          sudo apt install -y git zip unzip openjdk-17-jdk python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev cmake libffi-dev libssl-dev
          pip install --upgrade pip
          pip install buildozer cython==0.29.33

      - name: Buildozer ile derle
        run: |
          export BUILDOZER_VERBOSITY=2
          buildozer android debug

      - name: APK'yı Yükle
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: bin/*.apk
